question = inputbox("enter message:","apple box")
question = lcase(question)

for i = 1 to len(question)
	select case mid(question,i,1)
		case "a"
			encrypt = encrypt & "1/25, "
		case "b"
			encrypt = encrypt & "12/5, "
		case "c"
			encrypt = encrypt & "125, "
		case "d"
			encrypt = encrypt & "15/2, "
		case "e"
			encrypt = encrypt & "2/1345, "
		case "f"
			encrypt = encrypt & "25/14, "
		case "g"
			encrypt = encrypt & "5/12468, "
		case "h"
			encrypt = encrypt & "58/6, "
		case "i"
			encrypt = encrypt & "8/569, "
		case "j"
			encrypt = encrypt & "89, "
		case "k"
			encrypt = encrypt & "9/8, "
		case "l"
			encrypt = encrypt & "23/4, "
		case "m"
			encrypt = encrypt & "234, "
		case "n"
			encrypt = encrypt & "24/35, "
		case "o"
			encrypt = encrypt & "245, "
		case "p"
			encrypt = encrypt & "45/26, "
		case "q"
			encrypt = encrypt & "456, "
		case "r"
			encrypt = encrypt & "56/48, "
		case "s"
			encrypt = encrypt & "568, "
		case "t"
			encrypt = encrypt & "68/5, "
		case "u"
			encrypt = encrypt & "3/24, "
		case "v"
			encrypt = encrypt & "34/2, "
		case "w"
			encrypt = encrypt & "4/2356, "
		case "x"
			encrypt = encrypt & "46/5, "
		case "y"
			encrypt = encrypt & "6/4578, "
		case "z"
			encrypt = encrypt & "7, "
		case " "
			encrypt = encrypt & vbCrLf
		case else
	end select
next

msgbox encrypt,, "press [ctrl + c] to copy to clipboard"