question = inputbox("enter message:","keyboard")
question = lcase(question)

for i = 1 to len(question)
	select case mid(question,i,1)
		case "a"
			encrypt = encrypt & "11 "
		case "b"
			encrypt = encrypt & "555 "
		case "c"
			encrypt = encrypt & "333 "
		case "d"
			encrypt = encrypt & "33 "
		case "e"
			encrypt = encrypt & "3 "
		case "f"
			encrypt = encrypt & "44 "
		case "g"
			encrypt = encrypt & "55 "
		case "h"
			encrypt = encrypt & "66 "
		case "i"
			encrypt = encrypt & "8 "
		case "j"
			encrypt = encrypt & "77 "
		case "k"
			encrypt = encrypt & "88 "
		case "l"
			encrypt = encrypt & "99 "
		case "m"
			encrypt = encrypt & "777 "
		case "n"
			encrypt = encrypt & "666 "
		case "o"
			encrypt = encrypt & "9 "
		case "p"
			encrypt = encrypt & "0 "
		case "q"
			encrypt = encrypt & "1 "
		case "r"
			encrypt = encrypt & "4 "
		case "s"
			encrypt = encrypt & "22 "
		case "t"
			encrypt = encrypt & "5 "
		case "u"
			encrypt = encrypt & "7 "
		case "v"
			encrypt = encrypt & "444 "
		case "w"
			encrypt = encrypt & "2 "
		case "x"
			encrypt = encrypt & "222 "
		case "y"
			encrypt = encrypt & "6 "
		case "z"
			encrypt = encrypt & "111 "
		case " "
			encrypt = encrypt & vbCrLf
		case else
	end select
next

msgbox encrypt,, "press [ctrl + c] to copy to clipboard"