question = inputbox("enter message:","triangle")
question = lcase(question)

for i = 1 to len(question)
	select case mid(question,i,1)
		case "a"
			encrypt = encrypt & "001 "
		case "b"
			encrypt = encrypt & "002 "
		case "c"
			encrypt = encrypt & "010 "
		case "d"
			encrypt = encrypt & "011 "
		case "e"
			encrypt = encrypt & "012 "
		case "f"
			encrypt = encrypt & "020 "
		case "g"
			encrypt = encrypt & "021 "
		case "h"
			encrypt = encrypt & "022 "
		case "i"
			encrypt = encrypt & "100 "
		case "j"
			encrypt = encrypt & "101 "
		case "k"
			encrypt = encrypt & "102 "
		case "l"
			encrypt = encrypt & "110 "
		case "m"
			encrypt = encrypt & "111 "
		case "n"
			encrypt = encrypt & "112 "
		case "o"
			encrypt = encrypt & "120 "
		case "p"
			encrypt = encrypt & "121 "
		case "q"
			encrypt = encrypt & "122 "
		case "r"
			encrypt = encrypt & "200 "
		case "s"
			encrypt = encrypt & "201 "
		case "t"
			encrypt = encrypt & "202 "
		case "u"
			encrypt = encrypt & "210 "
		case "v"
			encrypt = encrypt & "211 "
		case "w"
			encrypt = encrypt & "212 "
		case "x"
			encrypt = encrypt & "220 "
		case "y"
			encrypt = encrypt & "221 "
		case "z"
			encrypt = encrypt & "222 "
		case " "
			encrypt = encrypt & vbCrLf
		case else
	end select
next

msgbox encrypt,, "press [ctrl + c] to copy to clipboard"